version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - ls -la
      #- npm i npm@latest -g
      - npm install yarn -g
  pre_build:
    commands:
      - yarn install
      - ls -la

artifacts:
  files:
    - '**/*'